apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webui
  name: webui
spec:
  volumes:
   - name: shavol
     hostPath:
      path: /var/run/docker.sock
      type: Socket
  containers:
  - image: portainer/portainer
    name: webui
    volumeMounts:
     - name: shavol
       mountPath: /var/run/docker.sock
    ports:
    - containerPort: 9000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
