apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: volapp
  name: volapp
spec:
  volumes:
   - name: volapp
     emptyDir: {} 
  containers:
  - image: alpine
    name: volapp
    volumeMounts: 
     - name: volapp
       mountPath: /mydata
    command: ["/bin/sh","-c","while true ; do date >> /mydata/output.txt; sleep 2;done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
