apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: appsvc
  name: appsvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: app
  type: NodePort
