apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p1
  name: p1
spec:
  containers:
  - image: alpine
    name: p1
    command: ["/bin/sh","-c","ping -i 10 8.8.8.8"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
