apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p2
  name: p2
spec:
  containers:
  - image: alpine
    name: p2
    command: ["/bin/sh","-c"]
    args:
     - "ping -i 10 8.8.8.8 > /tmp/data.txt"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
