apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p3
  name: p3
spec:
  containers:
  - image: busybox
    name: p3
    workingDir: /opt
    command: ["/bin/sh","-c"]
    args:
     - "sleep infinity"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
