apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: repc
  name: repc
spec:
  replicas: 2
  template: 
    metadata: 
     name: replicationcontrol
     labels:
      app: repc
    spec:
      containers:
       - image: nginx
         name: repc
         ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: repc
  name: repc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: repc
  type: NodePort
