apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecarpod
  name: sidecarpod
spec:
  containers:
  - image: alpine
    name: main
    command: ["/bin/sh","-c","ping 8.8.8.8"]
  - image: alpine
    name: sidecar
    command: ["/bin/sh","-c","sleep 10000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
