apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p2
  name: p2
spec:
  volumes: 
   - name: v2
     hostPath: 
      path: /etc
      type: Directory
  containers:
  - image: alpine
    name: p2
    volumeMounts: 
     - name: v2
       mountPath: /mydata
    command: ["/bin/sh","-c","while true; do wc -l /mydata/passwd; sleep 2; done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
