apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p3
  name: p3
spec:
  volumes: 
   - name: v3
     hostPath: 
      path: /etc/passwd
      type: File
  containers:
  - image: alpine
    name: p3
    volumeMounts: 
     - name: v3
       mountPath: /mydata/passwd
    command: ["/bin/sh","-c","while true; do wc -l /mydata/passwd; sleep 2; done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
