apiVersion: v1
kind: Service
metadata:
  name: my-nginx1
  labels:
    run: my-nginx1
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: my-nginx1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx1
spec:
  selector:
    matchLabels:
      run: my-nginx1
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx1
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      containers:
      - name: nginxhttps
        image: shashanksr/myappnginx:latest
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume

