apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shawebapp
  name: shawebapp
spec:
  containers:
  - image: shashanksr/shawebapp:latest
    name: shawebapp
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
