apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shasweb
    app: webapp
  name: shasweb
spec:
  containers:
  - image: nginx
    name: shasweb
    ports:
    - containerPort: 80
    resources: {}
  imagePullSecrets:
   - name: shashanksec
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

#kubectl create secret docker-registry shashanksec --docker-username=shashank --docker-password=redhat --docker-server=shashank.azurecr.io -n shashank
