apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shasweb
    app: webapp
  name: shasweb
spec:
  containers:
  - image: nginx
    name: shasweb
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
