apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar
  name: sidecar
spec:
  containers:
  - image: alpine
    name: sidecar # main container
    command: ["/bin/sh","-c","ping google.com"]
  - image: alpine
    name: sidecar1 #sidecar container
    command: ["/bin/sh","-c","sleep 10000"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
