apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecarvol
  name: sidecarvol
spec:
  volumes: 
   - name: shavol
     emptyDir: {}
  containers:
  - image: nginx
    name: main # main container
    ports:
     - containerPort: 80
    volumeMounts:
     - name: shavol
       mountPath: /usr/share/nginx/html/

  - image: alpine
    name: sidecar #sidecar container
    volumeMounts:
     - name: shavol
       mountPath: /random
    command: ["/bin/sh","-c"," while true ; do echo  '<h1> Hello all i Am SideCar </h1>'   >>/random/index.html; sleep 5; done"]  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
