apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    run: shashankreplicaset
  name: shashankreplicaset
spec:
  selector:
   matchLabels: 
    app: shashankreplicaset
  replicas: 2
  template:
   metadata:
    name: shashankreplicaset
    labels:
     app: shashankreplicaset
   spec:
     containers:
      - image: nginx
        name: shashankreplicaset
        ports:
         - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: shashankreplicaset
  name: shashankreplicaset
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: shashankreplicaset
